### PR TITLE
Fix running autorest-compare on windows

### PR DESCRIPTION
**Pull request by timotheeguerin**
There was some issues with the package-lock.json, so I regenerated it as well.

### CODE REVIEW

**Comment by daviwil** [comment]
I wonder if the SHA errors on Linux build have something to do with npm version mismatch between Windows and Linux on Azure Pipelines?  Pretty weird that it'd complain about that.

**Comment by timotheeguerin** [comment]
Yeah, i am looking into it, it was failing originally on windows and and remove package-lock and run npm install which fixed it but seems to have broken it for linux

**Comment by timotheeguerin** [comment]
Seems like I had global `npmrc` with some az devops registry which was causing all kind of issues.

**Review by daviwil — APPROVED** [review]
Nice!  Can you bump the patch version too so that I can ship the update once this is merged?

**Pull request merged**
